### PR TITLE
Fix PHP 8 compatibility.

### PR DESCRIPTION
**Pull request by demiankatz**
This PR addresses PHP 8 incompatibilities in the code and gets all tests passing (except for those which depend on other PEAR libraries which ALSO have PHP 8 incompatibilities).

### CODE REVIEW

**Comment by dbs** [comment]
@amir @davidcoallier - could one of you take a look? This blocks part of the functionality of File_MARC on PHP 8, and the fix here looks pretty straightforward.

**Comment by amir** [comment]
@dbs unfortunately I'm not familiar with changes in PHP 8 at all. Perhaps @kenguest or @ashnazg might be able to help?

**Comment by kenguest** [comment]
I'll take a look later today

**Review by kenguest — APPROVED** [review]
LGTM

**Comment by demiankatz** [comment]
Thank you very much, @dbs, @amir and @kenguest! Any idea when this can be included in a release? I'd love to get the fix into the next release of my project, if it's possible... but I can be patient if I have to. ;-)

**Comment by kenguest** [comment]
Hi @demiankatz - I hope to have a new release out either today or tomorrow, and possibly another release after than within a few more weeks.

**Comment by demiankatz** [comment]
That's great, @kenguest, I really appreciate the help!

**Comment by kenguest** [comment]
Validate 0.8.6 is available for download at https://pear.php.net/package/Validate/download/ now

**Comment by demiankatz** [comment]
Thanks, @kenguest; however, it seems like the new release is not yet available here on GitHub or in Packagist. Does a tag still need to be pushed up to make that happen?

**Comment by kenguest** [comment]
I don't have access to push a new release to packagist (@ashnazg can however). 

The changes are available on the https://packagist.org/packages/pear/validate#dev-master version though.

**Comment by demiankatz** [comment]
Thanks, good to know. In some cases, tagging a release in GitHub may automatically push to Packagist... but I don't know what the official PEAR practices are. In any case, if @ashnazg is able to help, I would be grateful, and if not, I can always pull the code using dev-master as a last resort.

**Comment by ashnazg** [comment]
v0.8.6 tagged in Github, and dev-master deleted on packagist... you should now be able to see v0.8.6 is the most recent release seen by composer.

**Comment by kenguest** [comment]
Thanks Chuck!

**Comment by demiankatz** [comment]
Thanks again, @ashnazg and @kenguest. Unfortunately, the adventure isn't over quite yet. All of these changes were designed to fix upstream problems in Validate_ISPN. Now that Validate is in better shape, it reveals some significant problems with Validate_ISPN. I have opened https://github.com/pear/Validate_ISPN/pull/5 to address these.

There is also a new problem here in composer.json -- it now requires EXACTLY php 7.3.0 and won't install in other versions. I've opened https://github.com/pear/Validate/pull/4 to address this problem. Unfortunately, I think we're going to have to repeat the whole release cycle after merging this latest PR in order to make the library truly usable everywhere.

**Pull request merged**
